version: '3.8'

services:
  podcast-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - PORT=8080
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp/podcast_files:/tmp/podcast_files
    restart: unless-stopped